### ISSUE TITLE
Klachtenformulier | NLDS form richtlijnen check

### ISSUE THREAD

**Issue by TessaViergever** [frameless/gemeentevoorbeeld.nl#461]
🌐 [NL Design System richtlijnen over formulieren](https://nldesignsystem.nl/richtlijnen/formulieren/)

## Doel

* Voor de niet ingelogde flow moeten deze punten gecontroleerd worden. Is het toegepast? Is het op de juiste manier toegepast? Evt. ontbrekende punten toevoegen of verkeerd toegepaste punten refactoren. 
* De ingelogde flow bestaat op dit moment nog niet. Hier kunnen deze punten vanaf het begin in meegenomen worden. 

## To-do's
- [ ]  [Autocomplete](https://nldesignsystem.nl/richtlijnen/formulieren/autocomplete/) toevoegen 
- [ ] Gebruik van [buttons](https://nldesignsystem.nl/richtlijnen/formulieren/buttons/) binnen het formulier nalopen. 
- [ ] [Succespagina](https://nldesignsystem.nl/richtlijnen/formulieren/bevestigingspagina/) (bevestigingspagina) checken | _(bijv. uitzoeken: verschillende of dezelfde pagina voor wel/niet ingelogd?)_ 
- [ ] [Descriptions](https://nldesignsystem.nl/richtlijnen/formulieren/descriptions/) gebruik checken. | _(bijv. in de niet ingelogde flow in stap 2: hier komt zonder description tag de textbox naast het label te staan in plaats van eronder.)_
- [ ] [Foutmeldingen](https://nldesignsystem.nl/richtlijnen/formulieren/foutmeldingen/) | _(bijv. op ingelogd: zijn deze er? Zijn ze goed toegepast?)_ 
- [ ] [ Labels](https://nldesignsystem.nl/richtlijnen/formulieren/labels/) 
- [ ] Gebruik van [Links](https://nldesignsystem.nl/richtlijnen/formulieren/links/) in formulier 
- [ ] [Meerdere stappen](https://nldesignsystem.nl/richtlijnen/formulieren/meerdere-stappen/)
- [ ] [Placeholders](https://nldesignsystem.nl/richtlijnen/formulieren/placeholders/) 
- [ ] [Toetsenbord](https://nldesignsystem.nl/richtlijnen/formulieren/toetsenbord/) 
- [ ] [Uitgevraagde informatie](https://nldesignsystem.nl/richtlijnen/formulieren/vragen/) 
- [ ] [Visueel ontwerp](https://nldesignsystem.nl/richtlijnen/formulieren/visueel-ontwerp/)
- [ ] [Fouten voorkomen](https://nldesignsystem.nl/richtlijnen/formulieren/voorkom-fouten/)
- [ ] [Wanneer welk element?](https://nldesignsystem.nl/richtlijnen/formulieren/wanneer-welk-form-element/)
